### ISSUE TITLE
Mongoose error 

### ISSUE THREAD

**Issue by inseokr** [inseokr/MERN_linkedspace#212]
[0] Found channel and now the index is being udpated
[0] Found channel and now the index is being udpated
[0] err=Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[0] (node:6564) UnhandledPromiseRejectionWarning: ParallelSaveError: Can't save() the same doc multiple times in parallel. Document: 5f838e48f2dc6b5cf003faed
[0]     at ParallelSaveError.MongooseError [as constructor] (C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\error\mongooseError.js:10:11)
[0]     at new ParallelSaveError (C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\error\parallelSave.js:18:17)
[0]     at model.Model.save (C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\model.js:434:20)
[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\src\server\routes\chatting\index.js:54:11
[0]     at CoreDocumentArray.forEach (<anonymous>)
[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\src\server\routes\chatting\index.js:49:39
[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\model.js:4598:16
[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\query.js:4351:12
[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\query.js:2849:28
[0]     at processTicksAndRejections (internal/process/task_queues.js:79:11)
[0] (node:6564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[0] chatting update called, channel = 5f83bee8f2dc6b5cf003fb00-child-5f85275aea1f804a4c5d33f3-Justin-dm-Yoobinindex= 0
[0] Found channel and now the index is being udpated
[0] chatting update called, channel = 5f83bee8f2dc6b5cf003fb00-child-5f85275aea1f804a4c5d33f3-Yoobin-dm-inseoindex= 0
[0] Found channel and now the index is being udpated
[0] chatting update called, channel = 5f83bee8f2dc6b5cf003fb00-child-5f85275aea1f804a4c5d33f3-Justin-dm-Yoobinindex= 0
[0] Found channel and now the index is being udpated
[0] chatting update called, channel = 5f83bee8f2dc6b5cf003fb00-child-0-Justin-Yoobinindex= 6
[0] Found channel and now the index is being udpated
[0] Found channel and now the index is being udpated
[0] err=Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[0] (node:6564) UnhandledPromiseRejectionWarning: ParallelSaveError: Can't save() the same doc multiple times in paralle[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\model.js:4598:16
[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\query.js:4351:12
[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\query.js:2849:28
[0]     at processTicksAndRejections (internal/process/task_queues.js:79:11)
[0] (node:6564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[0] chatting update called, channel = 5f83bee8f2dc6b5cf003fb00-child-5f85275aea1f804a4c5d33f3-Justin-dm-Yoobinindex= 0
[0] Found channel and now the index is being udpated
[0] chatting update called, channel = 5f83bee8f2dc6b5cf003fb00-child-5f85275aea1f804a4c5d33f3-Yoobin-dm-inseoindex= 0
[0] Found channel and now the index is being udpated
[0] chatting update called, channel = 5f83bee8f2dc6b5cf003fb00-child-5f85275aea1f804a4c5d33f3-Justin-dm-Yoobinindex= 0
[0] Found channel and now the index is being udpated
[0] chatting update called, channel = 5f83bee8f2dc6b5cf003fb00-child-0-Justin-Yoobinindex= 6
[0] (node:6564) UnhandledPromiseRejectionWarning: ParallelSaveError: Can't save() the same doc multiple times in parallel. Document: 5f838e48f2dc6b5cf003faed
[0]     at ParallelSaveError.MongooseError [as constructor] (C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\error\mongooseError.js:10:11)
[0]     at new ParallelSaveError (C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\error\parallelSave.js:18:17)
[0]     at model.Model.save (C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\model.js:434:20)
[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\src\server\routes\chatting\index.js:54:11
[0]     at CoreDocumentArray.forEach (<anonymous>)
[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\src\server\routes\chatting\index.js:49:39
[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\model.js:4598:16
[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\query.js:4351:12
[0]     at C:\Users\inseo\linkedspaces\MERN_linkedspace\node_modules\mongoose\lib\query.js:2849:28
[0]     at processTicksAndRejections (internal/process/task_queues.js:79:11)
[0] (node:6564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[0] Found channel and now the index is being udpated
[0] Found channel and now the index is being udpated
[0] err=Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Terminate batch job (Y/N)? [0] ^CTerminate batch job (Y/N)? node ./src/se

**Comment by inseokr** [comment]
Problem is not observed anymore.
