### ISSUE TITLE
Deploy the service to Heroku

### ISSUE THREAD

**Issue by inseokr** [inseokr/MERN_linkedspace#235]

**Comment by inseokr** [comment]
I just created a linkedspace app, and link it to the heroku. 

Built failed though.

**Comment by inseokr** [comment]
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.19.0...
       Using default npm version: 6.14.8
       
-----> Installing dependencies
       Installing node modules
       
       > websocket@1.0.31 install /tmp/build_3e6beb0c_/node_modules/websocket
       > (node-gyp rebuild 2> builderror.log) || (exit 0)
       
       make: Entering directory '/tmp/build_3e6beb0c_/node_modules/websocket/build'
         CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
         SOLINK_MODULE(target) Release/obj.target/bufferutil.node
         COPY Release/bufferutil.node
         CXX(target) Release/obj.target/validation/src/validation.o
         SOLINK_MODULE(target) Release/obj.target/validation.node
         COPY Release/validation.node
       make: Leaving directory '/tmp/build_3e6beb0c_/node_modules/websocket/build'
       
       > styled-components@4.4.1 postinstall /tmp/build_3e6beb0c_/node_modules/styled-components
       > node ./scripts/postinstall.js || exit 0
       
       Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
       
       > core-js-pure@3.6.4 postinstall /tmp/build_3e6beb0c_/node_modules/core-js-pure
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > cwebp-bin@5.1.0 postinstall /tmp/build_3e6beb0c_/node_modules/cwebp-bin
       > node lib/install.js
       
         ⚠ Command failed: /tmp/build_3e6beb0c_/node_modules/cwebp-bin/vendor/cwebp -version
       /tmp/build_3e6beb0c_/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
       
       
         ⚠ cwebp pre-build test failed
         ℹ compiling from source
         ✔ cwebp built successfully
       
       > pngquant-bin@5.0.2 postinstall /tmp/build_3e6beb0c_/node_modules/pngquant-bin
       > node lib/install.js
       
         ✔ pngquant pre-build test passed successfully
       
       > optipng-bin@6.0.0 postinstall /tmp/build_3e6beb0c_/node_modules/optipng-bin
       > node lib/install.js
       
         ✔ optipng pre-build test passed successfully
       
       > mozjpeg@6.0.1 postinstall /tmp/build_3e6beb0c_/node_modules/mozjpeg
       > node lib/install.js
       
         ✔ mozjpeg pre-build test passed successfully
       
       > gifsicle@4.0.1 postinstall /tmp/build_3e6beb0c_/node_modules/gifsicle
       > node lib/install.js
       
         ✔ gifsicle pre-build test passed successfully
       
       > core-js@2.6.10 postinstall /tmp/build_3e6beb0c_/node_modules/core-js
       > node postinstall || echo "ignore"
       
       
       > fsevents@1.2.9 install /tmp/build_3e6beb0c_/node_modules/fsevents
       > node install
       
       
       > uglifyjs-webpack-plugin@0.4.6 postinstall /tmp/build_3e6beb0c_/node_modules/uglifyjs-webpack-plugin
       > node lib/post_install.js
       
       
       > nodemon@1.19.4 postinstall /tmp/build_3e6beb0c_/node_modules/nodemon
       > node bin/postinstall || exit 0
       
       Love nodemon? You can now support the project via the open collective:
        > https://opencollective.com/nodemon/donate
       
       
       > deasync@0.1.15 install /tmp/build_3e6beb0c_/node_modules/deasync
       > node ./build.js
       
       `linux-x64-node-12` exists; testing
       Binary is fine; exiting
       added 2921 packages in 100.331s
       
-----> Build
       Running build
       
       > linkedspaces@1.0.0 build /tmp/build_3e6beb0c_
       > webpack --mode development
       
/tmp/build_3e6beb0c_/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports (/tmp/build_3e6beb0c_/webpack.config.js:14:26)
    at handleFunction (/tmp/build_3e6beb0c_/node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)
    at prepareOptions (/tmp/build_3e6beb0c_/node_modules/webpack-cli/bin/utils/prepareOptions.js:9:5)
    at requireConfig (/tmp/build_3e6beb0c_/node_modules/webpack-cli/bin/utils/convert-argv.js:117:14)
    at /tmp/build_3e6beb0c_/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/tmp/build_3e6beb0c_/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /tmp/build_3e6beb0c_/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/tmp/build_3e6beb0c_/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /tmp/build_3e6beb0c_/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/tmp/build_3e6beb0c_/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/build_3e6beb0c_/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! linkedspaces@1.0.0 build: `webpack --mode development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the linkedspaces@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.Scp7i/_logs/2020-10-26T21_41_31_468Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by inseokr** [comment]
Most likely it's happening because ".env" file is missing?

**Comment by inseokr** [comment]
It's deployed, but app didn't start successfully.
