### ISSUE TITLE
WebSocket not established in heroku environment

### ISSUE THREAD

**Issue by inseokr** [inseokr/MERN_linkedspace#237]
Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at http://linkedspaces.herokuapp.com/bundle.js:81:112640
    at v (http://linkedspaces.herokuapp.com/bundle.js:42:74495)
    at Generator._invoke (http://linkedspaces.herokuapp.com/bundle.js:42:74248)
    at Generator.forEach.e.<computed> [as next] (http://linkedspaces.herokuapp.com/bundle.js:42:74675)
    at St (http://linkedspaces.herokuapp.com/bundle.js:81:103402)
    at a (http://linkedspaces.herokuapp.com/bundle.js:81:103606)
    at http://linkedspaces.herokuapp.com/bundle.js:81:103667
    at new Promise (<anonymous>)
    at http://linkedspaces.herokuapp.com/bundle.js:81:103546
    at be (http://linkedspaces.herokuapp.com/bundle.js:81:113375)

**Comment by inseokr** [comment]
Server Side

const express = require('express');
const { Server } = require('ws');
var fileUpload         = require('express-fileupload');

const PORT = process.env.PORT || 3000;
const INDEX = '/index.html';

/*const server = express()
  .use((req, res) => res.sendFile(INDEX, { root: __dirname }))
  .listen(PORT, () => console.log(`Listening on ${PORT}`));*/

const server = express().listen(PORT, () => console.log(`Listening on ${PORT}`));


console.log("server = " + JSON.stringify(server));

const wss = new Server({ server });



Cliet Side

let HOST = window.location.origin.replace(/^http/,'ws');
let ws = new WebSocket(HOST);
