### ISSUE TITLE
node.js - parallel saving

### ISSUE THREAD

**Issue by inseokr** [inseokr/MERN_linkedspace#339]
readListingFromFriends: found listing!!
(node:27252) UnhandledPromiseRejectionWarning: ParallelSaveError: Can't save() the same doc multiple times in parallel. Document: 5fe806e4a56aab629c828707
    at model.Model.save (C:\Users\inseo\linkedspaces\clean_master\MERN_linkedspace\node_modules\mongoose\lib\model.js:463:20)
    at C:\Users\inseo\linkedspaces\clean_master\MERN_linkedspace\src\server\routes\chatting\index.js:51:18
    at CoreDocumentArray.forEach (<anonymous>)
    at C:\Users\inseo\linkedspaces\clean_master\MERN_linkedspace\src\server\routes\chatting\index.js:47:44
    at C:\Users\inseo\linkedspaces\clean_master\MERN_linkedspace\node_modules\mongoose\lib\model.js:4846:16
    at C:\Users\inseo\linkedspaces\clean_master\MERN_linkedspace\node_modules\mongoose\lib\model.js:4846:16
    at C:\Users\inseo\linkedspaces\clean_master\MERN_linkedspace\node_modules\mongoose\lib\helpers\promiseOrCallback.js:24:16
    at C:\Users\inseo\linkedspaces\clean_master\MERN_linkedspace\node_modules\mongoose\lib\model.js:4869:21
    at C:\Users\inseo\linkedspaces\clean_master\MERN_linkedspace\node_modules\mongoose\lib\query.js:4424:11
    at C:\Users\inseo\linkedspaces\clean_master\MERN_linkedspace\node_modules\kareem\index.js:135:16
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:27252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by inseokr** [comment]
This is happening because channels are added multiple time. It's a problem which's supposed to be addressed by now.
This is happening because new is called multiple times.

**Comment by inseokr** [comment]
loadChattingDatabase should be done with some delay... 
I think we need more solid logic around. 
new shouldn't be called while it's being created...

**Comment by inseokr** [comment]
Issue still exists.

**Comment by inseokr** [comment]
loadChatHistory will call setChannelContexts.
And this may trigger loadChattingDatabase again.

**Comment by inseokr** [comment]
suppressed loadChattingDatabase upon loadChatHistory.

**Comment by inseokr** [comment]
Not sure if it's better now... but at least it seems to be working better now.
