### ISSUE TITLE
Server crashes - clicking one of contacts in the list

### ISSUE THREAD

**Issue by inseokr** [inseokr/MERN_linkedspace#92]
Chat Server: received data = CSC:Register:justinid = 9f325ea4-1c10-429d-ad79-58edc8caf20d
Yay, now I could register the socket
chatting update called, channel = inseo-dm-justinindex= 2
Found channel and now the index is being udpated
Found channel and now the index is being udpated
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:526:11)
    at ServerResponse.header (C:\webdev\mern\MERN_linkedspace\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\webdev\mern\MERN_linkedspace\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (C:\webdev\mern\MERN_linkedspace\node_modules\express\lib\response.js:267:15)
    at C:\webdev\mern\MERN_linkedspace\src\server\routes\chatting\index.js:55:10
    at CoreDocumentArray.forEach (<anonymous>)
    at C:\webdev\mern\MERN_linkedspace\src\server\routes\chatting\index.js:49:39
    at C:\webdev\mern\MERN_linkedspace\node_modules\mongoose\lib\model.js:4598:16
    at C:\webdev\mern\MERN_linkedspace\node_modules\mongoose\lib\query.js:4351:12
    at C:\webdev\mern\MERN_linkedspace\node_modules\mongoose\lib\query.js:2849:28
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Emitted 'error' event on Function instance at:
    at C:\webdev\mern\MERN_linkedspace\node_modules\mongoose\lib\model.js:4600:13
    at C:\webdev\mern\MERN_linkedspace\node_modules\mongoose\lib\query.js:4351:12
    at C:\webdev\mern\MERN_linkedspace\node_modules\mongoose\lib\query.js:2849:28
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simple-react-full-stack@1.0.0 start: `npm run build && node ./src/server/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simple-react-full-stack@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by inseokr** [comment]
![image](https://user-images.githubusercontent.com/4754808/88001692-9b342a80-cab5-11ea-8229-e0aca610eb94.png)

Duplicate channel found in the dm_channels

**Comment by inseokr** [comment]
I don't see the problem anymore.... let's wait till the issue is reproduced again.
